Module: ServerlessPatterns.BitcoinActivity
Description: Sample API for Bitcoin transactions
Items:

  - Import: BitcoinPriceTable
    Module: ServerlessPatterns.BitcoinTable::Table
    Type: AWS::DynamoDB::Table
    Scope: RecordFunction
    Allow:
      - dynamodb:Query

  - Function: RecordFunction
    Memory: 256
    Timeout: 30
    Sources:
      - Api: POST:/buy
        Invoke: Buy
      - Api: POST:/sell
        Invoke: Sell

  - Resource: Table
    Type: AWS::DynamoDB::Table
    Scope: RecordFunction, public
    Allow:
      - dynamodb:PutItem
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  - Variable: ApiUrl
    Description: API Gateway URL
    Scope: public
    Value: !Ref Module::RestApi::Url